# This file generates the GitHub Actions matrix
---
include:
  - board: nice_nano_v2
    shield: cradio_left
  - board: nice_nano_v2
    shield: cradio_right
#  - board: nice_nano_v2
#    shield: settings_reset
