# This file generates the GitHub Actions matrix
---
include:
  # akohekohe
  - board: seeeduino_xiao_ble
    shield: akohekohe rgbled_adapter
    
  - board: seeeduino_xiao_ble
    shield: akohekohe rgbled_adapter
    snippet: zmk-usb-logging
    cmake-args: -DCONFIG_LOG_PROCESS_THREAD_STARTUP_DELAY_MS=8000
    artifact-name: akohekohe_with_logging

  # rommana
  - board: seeeduino_xiao_ble
    shield: rommana_dongle dongle_display
    artifact-name: rommana_central_dongle
  - board: seeeduino_xiao_ble
    shield: rommana_left rgbled_adapter
    artifact-name: rommana_central_left
  - board: seeeduino_xiao_ble
    shield: rommana_left rgbled_adapter
    cmake-args: -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
    artifact-name: rommana_peripheral_left
  - board: seeeduino_xiao_ble
    shield: rommana_right rgbled_adapter
    artifact-name: rommana_peripheral_right
    
  - board: seeeduino_xiao_ble
    shield: rommana_dongle dongle_display
    snippet: zmk-usb-logging
    cmake-args: -DCONFIG_LOG_PROCESS_THREAD_STARTUP_DELAY_MS=8000
    artifact-name: rommana_central_dongle_with_logging

  # sweep
  - board: seeeduino_xiao_ble
    shield: sweep_dongle dongle_display
    artifact-name: sweep_central_dongle
  - board: nice_nano_v2
    shield: sweep_left led_indicator
    artifact-name: sweep_central_left
  - board: nice_nano_v2
    shield: sweep_left led_indicator
    cmake-args: -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
    artifact-name: sweep_peripheral_left
  - board: nice_nano_v2
    shield: sweep_right led_indicator
    artifact-name: sweep_peripheral_right
    
  - board: nice_nano_v2
    shield: sweep_left led_indicator
    snippet: zmk-usb-logging
    cmake-args: -DCONFIG_LOG_PROCESS_THREAD_STARTUP_DELAY_MS=8000
    artifact-name: sweep_central_left_with_logging

  # reset
  - board: seeeduino_xiao_ble
    shield: settings_reset
  - board: nice_nano_v2
    shield: settings_reset
